website/css/_base.scss, website/css/components/BackToTopButton.scss, website/css/components/DropdownItem.scss, website/js/browser.js, website/js/utils.js
and back to top button on iOS. Tapping it causes the bottom nav to show up (default behavior of Safari).
=> fix sticky hover mobile

package-lock.json, package.json, website/js/components/Markdown.js, website/js/components/Question.js
Increases performance of UI interactions significantly (around 3x)
=> perf optimizations

questions/big-o-notation.md, questions/cache-busting.md, questions/event-delegation.md, questions/memoize.md, questions/recursion.md, questions/rest.md, questions/var-let-const.md, questions/virtual-dom.md, questions/xss.md, scripts/extract.js, website/css/components/DropdownItem.scss, website/js/state.js
Adds questions suggested by reddit and other concepts that are important
=> Add questions (reddit, elsewhere)

README.md, questions/object-creation.md, questions/prototypal-inheritance.md
[Beware](https://www.reddit.com/r/javascript/comments/6q2lk0/why_composition_is_harder_with_classes/dku34cl/)1 [referencing](https://www.reddit.com/r/javascript/comments/5c5lkq/what_eric_elliot_wants_to_say_can_somebody/d9u6tv3/)2 or [learning](https://www.reddit.com/r/javascript/comments/837t82/who_are_some_of_your_favorite_speakers_educators/dvh0br6/)3 from Eric Elliott.
* He is frequently -- almost habitually -- wrong.
* He behaves like a con-man. As another user put it, "What Eric is doing is like a scam artist talking about 'quantum effects' and 'toxin cleansing'. Scammers ride on the popularity of some accepted terms, but reject their meaning and make up some B.S."
* Folks who actually paid for his workshop said it felt like snakeoil.
As for the other two lines I removed, that class …
=> Beware referencing or learning from Eric Elliott

questions/cors.md, questions/em-rem-difference.md
I have added two new questions. They're nearly done, they just need a bit of polishing by @atomiks imo.
=> New questions

questions/batches.md, questions/bind-function.md, questions/expression-vs-statement.md, questions/falsy-truthy.md, questions/imperative-vs-declarative.md, questions/semicolons.md, questions/short-circuit-evaluation.md
=> add questions

questions/callback-hell.md
there is a error 
```js
const e = await getMoreData(e)
```
should be like below
```js
const e = await getMoreData(d)
```
**Resolves** #(issue number)
=> fix: a param error of getMoreData function

questions/big-o-notation.md
As long as the math checks out(from wolfram) it should work just fine, but I'm not sure it is right? I may just be tired though... it's been a rough week
**Resolves** #83  
NOTE: Reason I'm not saying I've fixed it is because I'm not sure I calculated the big Otation correctly... I've had a long week and little errors are slipping by easier than they should be
=> Fix #83 Big O Notation: missed the time taken and the NlogN math

questions/big-o-notation.md
Add binary search algorithm as an example of logarithmic time complexity 
**Resolves** #(issue number)
=> Add logarithmic time complexity

questions/cors.md
Fixed a typo in the CORS question: exmaple => example
=> Fix typo: exmaple => example

questions/html-vs-xhtml.md
Fixed a typo in the HTML vs XHTML question: ands => and
Sorry just found another one when the other PR was merged already.
=> Fix typo: ands => and

questions/closures-example.md
The snippet of code shows an example of closures usage and ES6 syntax. It's a very popular question asked during interviews
=> Add closures example

questions/generator-function.md
=> [Question] Add generator question

README.md, data/questions.json, questions/use-strict.md
Small typo fix: `enfores` to `enforces`
=> Fix typo: enfores to enforces

questions/for-each-map.md
```diff
-...`map()` maps each element to new element by invoking the callback function on each element and returns a new array...
+...`map()` maps each element to a new element by invoking the callback function on each element and returning a new array...
```
=> [ENHANCEMENT] Fix missing word & keep tense consistent

questions/mime.md
Hi there!
This PR includes an intermediate JS category question: `What is a MIME type and what is it used for?`. It also includes the answer, good to hear and additional links content. 
Please let me know if you want to add or propose anything else to be more clear in the question, answer, good to hear or links section. 
Thanks! 🚀
=> [FEATURE] Adding MIME Type question

data/questions.json, package-lock.json, questions/class-name.md, questions/error-boundaries.md, questions/hoc-component.md, questions/lifecycle-methods.md, questions/lifecycle.md, questions/lift-state.md, questions/prop-validation.md, questions/react-comments.md, website/css/_vars.scss, website/css/components/DropdownItem.scss, website/css/components/Question.scss, website/js/state.js, website/js/utils.js
=> React questions

questions/callback-in-setState.md
Just a simple typo change.
Made a change to line 15 - corrected "functio" to read "function"
* [ *] General / Things regarding the repository (like CI Integration)
* [ *] Enhancement (non-breaking improvement of a question)
* [ *] My code follows the code style of this project.
* [ *] I have checked that there isn't any PR doing the same
* [ *] I have read the **CONTRIBUTING** document.
=> [ENHANCEMENT] fixed typo in callback-in-setState.md

questions/stateless-components.md
Changes made:
-fixed typos/errors:
Should be stateless (not stateful). 
'Stateless class components should be preferred when lifecycle hooks [don't] need to be used.'
=> [FIX] Questions: update stateless component answer

README.md
Fix time complexity for quick sort algorithm in [What is Big O Notation?](https://github.com/30-seconds/30-seconds-of-interviews/blob/master/README.md#what-is-big-o-notation) to be NlogN not logN
=> [FIX] time complexity for quick sort algorithm

static-parts/README-start.md
=> [ENHANCEMENT] Add links to other repositories

README.md, data/questions.json, questions/inline-conditional-expressions.md
There  shouldn't be a semi-colon mixed with jsx outside of curly braces.
* [ x] Website
* [ x] Enhancement (non-breaking improvement of a question)
* [x ] My code follows the code style of this project.
* [x ] I have updated the documentation accordingly.
* [x ] I have checked that there isn't any PR doing the same
* [x ] I have read the **CONTRIBUTING** document.
=> removing a semicolon that shouldn't be there

website/js/components/Markdown.js
Refactor `memoMarked()` to resolve `no-return-assign` eslint error and hopefully improve readability.
=> [FIX] Fix `no-return-assign` linting error

questions/lexical-vs-dynamic-scoping.md
Add a new question about lexical scoping vs. dynamic scoping.
=> [QUESTION] Lexical scoping vs. dynamic scoping

questions/lifecycle-methods.md, questions/lifecycle.md
The 2 questions re: the React lifecycle had information about the old methods used from before React 16.3 was released. I added these new methods with explanations, and a picture Dan Abramov had made.
- Added the `getDerivedStateFromProps`, `getSnapshotBeforeUpdate`, and `componentWillCatch` lifecycle methods to 2 questions
- Removed `componentWillMount`, `componentWillReceiveProps`, and `componentWillUpdate` lifecycle methods from 2 questions
- Added a picture from Dan Abramov to 1 question
=> [ENHANCEMENT] React lifecycle questions updated with new methods

website/js/components/Markdown.js, website/js/components/Question.js
Accidentally didn't test build script on #126 and merged it even if the build script didn't work. Reverted all changes back so everything works now.
As proposed in #114 I added id's to each question so people can now share questions simply by sharing `link/#question-name`
**Resolves** #114
=> [FIX & FEATURE] fix bug with build & add id's on questions

data/questions.json
=> fix typo (remove duplicated word)

questions/big-o-notation.md
=> fix:the question of 'What is Big O Notation'

data/questions.json, scripts/extract.js, scripts/util.js
Added getSection and getFirstSection functions to util.js. Used them to get markdown sections correctly in extract.js. Also checked in questions.json after running the fixed extractor.
**Resolves** #139
=> [FIX: #139] Fix bug when a question is missing a section

data/questions.json, questions/inline-conditional-expressions.md
Remove redundant semicolon in answer for `What is inline conditional expressions?`
=> style: remove redundant semicolon

questions/callback-in-setState.md, questions/callback-refs-vs-finddomnode.md, questions/children-prop.md, questions/class-name.md, questions/context.md, questions/element-vs-component.md, questions/error-boundaries.md, questions/fragments.md, questions/hoc-component.md, questions/html-vs-react-event-handling.md, questions/inline-conditional-expressions.md, questions/keys.md, questions/lifecycle.md, questions/methods-context-react-classes.md, questions/passing-arguments-to-event-handlers.md, questions/portals.md, questions/prop-validation.md, questions/react-comments.md, questions/refs.md, questions/stateful-components.md, questions/stateless-components.md
I noticed many low quality questions (the new React ones), these are an effort to clean them up (grammar, syntax highlighting, consistency, etc).
=> Fix React questions

.gitignore, questions/postfix-vs-prefix-increment.md
1. Adding Adding `.idea` in .gitignore, which making Webstorm and other IntelliJ IDE works with this repo.
2.  think it should be `when` rather than `what`. Am I right?
=> [FEATURE] Adding .idea in .gitignore

website/js/components/RecommendedResource.js
Updating the link of Front End Handbook.
=> Update the year to 2019 of the Front End Handbook

questions/alt-attribute.md
This PR is just a copyedit/typo so most of the issue template was N/A. Feel free to close if not helpful!
=> FIX: Copyedit to alt attribute

questions/bem.md
Original link is broken, seems to no longer exist. (There is a copy of it here `[Writing clean and maintainable CSS using BEM methodology](https://www.bitcoininsider.org/article/23106/writing-clean-and-maintainable-css-using-bem-methodology)`, but some of the formatting is off, not sure if worth noting?)
Gave suggestion of an alternative BEM link.
This PR is just a copyedit so most of the issue template was N/A.
=> FIX: Update broken link on CSS BEM

questions/batches.md
Small grammer fixes.
* Questions / Answers
* Enhancement (non-breaking improvement of a question)
*  I have checked that the changes are working properly
*  I have checked that there isn't any PR doing the same
=> [ENHANCEMENT]

website/js/components/Footer.js
Updated outdated Hyperapp homepage link
=> Update Outdated Hyperapp homepage link

questions/accessibility-tree.md
=> Added a question for accessibility #172

questions/landmark-roles.md
=> adding a11y question for #172

questions/wcag.md
=> adding wcag a11y question

questions/accessibility-aria.md
Created an accessibility question with answer about WAI-ARIA.
**Adds to** #172
=> Fix: #172, Enhancement, Create aria a11y question and answer 

questions/accessibility-aria.md
Created an accessibility question with answer about WAI-ARIA.
**Adds to** #172
=> Fix: #172, Enhancement, Create ARIA accessibility question & answer

README.md, data/questions.json, questions/accessibility-aria.md, scripts/extract.js, scripts/util.js
Thanks to awesome contributions during first days of Hacktoberfest I am introducing the accessibility category. 
This is just `README.md` for now. The full website, with all categories, will come in the 2nd version very soon.
=> [FEATURE]  add accessibility category to builder script and fix question typos

questions/accessibility-contrast.md
Created an accessibility question with answer about contrast ratio.
**Adds to** #172
=> Fix: #172, Enhancement, Create contrast accessibility question

questions/handling-route-changes-in-single-page-apps.md
Contributes accessibility question towards Issue #172 , detailing how focus can be handled on route change in single page applications
=> #172 Feature - Add question on handling focus in single page app route changes

questions/accessibility-testing.md
Added question about tools for accessibility testing
=> Fix: #172 Add question about accessibility testing

questions/find-the-anagrams.md
Add new question for how to find and output groups of anagrams
=> [QUESTION] Add find and output the anagrams from a list

questions/debouncing.md
Added new question on debouncing in JS
=> Added question on debouncing

README.md
FIX: 30-seconds-of-css link in README
30-seconds-of-css link in README.md file was broken, so I replaced it with a correct one.
=> fix CSS link in README
